[workspace]
members = [
    "approx",
    "approx-derive",
]
resolver = "2"

[workspace.package]
version = "0.6.0-rc2"
edition = "2021"

[workspace.dependencies]
approx-derive = { path="approx-derive" }
